# Generated by Django 4.0.5 on 2022-06-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_users_options_users_address_users_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(default='media/img/user/default/default-profile.png', upload_to='media/img/user/profile-img'),
        ),
    ]
