# Generated by Django 4.0.5 on 2022-06-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_users_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
