# Generated by Django 4.0.5 on 2022-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_useraccountstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Invitation Send'), ('1', 'Approved'), ('2', 'Pending Approval'), ('3', 'Pendind Review'), ('4', 'Rejected'), ('5', 'Terminated')], default='0', max_length=50, null=True),
        ),
    ]
