# Generated by Django 4.0.5 on 2022-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_users_designation_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(default='img/user/default/default-profile.png', upload_to='img/user/profile-img'),
        ),
    ]
