# Generated by Django 4.0.5 on 2022-06-11 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='onboarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(default='default/default-profile.png', upload_to='img/user/profile-img'),
        ),
    ]
