# Generated by Django 4.0.5 on 2022-06-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Entitlements',
            },
        ),
        migrations.CreateModel(
            name='RoleEntitlements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entitlements.entitlements', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Role Entitlements',
            },
        ),
    ]
