# Generated by Django 4.0.5 on 2022-06-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleentitlements',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
