# Generated by Django 4.0.5 on 2022-06-20 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_useraccountstatus_status'),
        ('entitlements', '0003_roleentitlements_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleentitlements',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.userroles'),
        ),
    ]
