# Generated by Django 4.0.5 on 2022-06-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0004_alter_roleentitlements_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlements',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entitlements',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
