# Generated by Django 4.0.5 on 2022-06-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0005_alter_entitlements_name_alter_entitlements_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleentitlements',
            name='entitlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entitlements.entitlements'),
        ),
    ]
